--create database CINE_ESTRELLAS3
--go 

--drop database CINE_ESTRELLASOS

USE CINE_ESTRELLAS3
--go

--set dateformat dmy

-- TABLA TIPOS DOCUMENTO
CREATE TABLE TIPOS_DOCUMENTOS(
IDTIPO_DNI INT IDENTITY (1,1)  ,
DESCRIPCION VARCHAR (50) NOT NULL,
CONSTRAINT PK_IDTIPO_DNI PRIMARY KEY (IDTIPO_DNI)
)

-- TABLA GENEROS
CREATE TABLE GENEROS(
ID_GENERO INT IDENTITY (1,1) ,
DESCRIPCION VARCHAR (30) NOT NULL,
CONSTRAINT PK_ID_GENERO PRIMARY KEY (ID_GENERO)
)

-- TABLA PROVINCIAS
CREATE TABLE PROVINCIAS(
ID_PROVINCIA INT IDENTITY (1,1),
NOMBRE VARCHAR (50) NOT NULL,
CONSTRAINT PK_ID_PROVINCIA PRIMARY KEY (ID_PROVINCIA)
)

-- TABLA FORMAS DE PAGO
CREATE TABLE FORMAS_PAGO(
IDFORMA_PAGO INT IDENTITY (1,1),
DESCRIPCION VARCHAR (30) NOT NULL,
CONSTRAINT PK_IDFORMA_PAGO PRIMARY KEY (IDFORMA_PAGO)
)

-- TIPOS DE VENTA
CREATE TABLE TIPOS_VENTAS(
IDTIPO_VENTA INT IDENTITY (1,1) ,
DESCRIPCION VARCHAR (50) NOT NULL,
CONSTRAINT PK_IDTIPO_VENTA PRIMARY KEY (IDTIPO_VENTA)
)

-- TABLA PROMOCIONES
CREATE TABLE PROMOCIONES(
ID_PROMOCION INT IDENTITY (1,1)  ,
DESCRIPCION VARCHAR (50) NOT NULL,
CONSTRAINT PK_ID_PROMOCION PRIMARY KEY (ID_PROMOCION)
)

-- TABLA CLASIFICACIONES
CREATE TABLE CLASIFICACIONES(
ID_CLASIFICACION INT IDENTITY (1,1) NOT NULL,
NOMBRE VARCHAR (30),
DESCRIPCION VARCHAR (100),
CONSTRAINT PK_ID_CLASIFICACION PRIMARY KEY (ID_CLASIFICACION)
)

-- TABLA GENEROS PELICULAS
CREATE TABLE GENEROS_PELICULAS(
IDGENERO_PELICULA INT IDENTITY (1,1)  ,
DESCRIPCION VARCHAR (30) NOT NULL,
CONSTRAINT PK_IDGENERO_PELICULA PRIMARY KEY (IDGENERO_PELICULA)
)

-- TABLA VERSIONES
CREATE TABLE VERSIONES(
ID_VERSION INT IDENTITY (1,1)  ,
DESCRIPCION VARCHAR (50) NOT NULL,
CONSTRAINT PK_ID_VERSION PRIMARY KEY (ID_VERSION)
)

-- TABLA TIPOS ENTRADAS
CREATE TABLE TIPOS_ENTRADAS(
IDTIPO_ENTRADA INT IDENTITY (1,1)  ,
DESCRIPCION VARCHAR (50) NOT NULL,
CONSTRAINT PK_IDTIPO_ENTRADA PRIMARY KEY (IDTIPO_ENTRADA)
)

--TABLA TIPOS SALAS
CREATE TABLE TIPOS_SALAS(
IDTIPO_SALA INT IDENTITY (1,1) NOT NULL,
NOMBRE VARCHAR (30),
DESCRIPCION VARCHAR (200),
PRECIO DECIMAL,
CONSTRAINT PK_IDTIPO_SALA PRIMARY KEY (IDTIPO_SALA)
)

--TABLA CLIENTES
CREATE TABLE CLIENTES(
ID_CLIENTE INT IDENTITY (1,1)  ,
NOMBRE VARCHAR (50) NOT NULL,
APELLIDO VARCHAR (50) NOT NULL,
IDTIPO_DOCUMENTO INT NOT NULL,
NRO INT NOT NULL,
DIRECCION VARCHAR (150) NOT NULL,
FECHA_NAC DATE NOT NULL,
E_MAIL VARCHAR (100) NOT NULL,
TELEFONO DECIMAL,
ID_GENERO INT NOT NULL,
CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE),
CONSTRAINT FK_ID_GENERO FOREIGN KEY (ID_GENERO) REFERENCES GENEROS (ID_GENERO),
CONSTRAINT FK_IDTIPO_DNI FOREIGN KEY (IDTIPO_DOCUMENTO) REFERENCES TIPOS_DOCUMENTOS (IDTIPO_DNI)
)

--TABLA SUCURSALES
CREATE TABLE SUCURSALES(
ID_SUCURSAL INT IDENTITY (1,1)  ,
NOMBRE_FANTASIA VARCHAR (50) NOT NULL,
RAZON_SOCIAL VARCHAR (50) NOT NULL,
CUIT INT NOT NULL,
ING_BRUTO DECIMAL NOT NULL,
DIRECCION VARCHAR (50) NOT NULL,
E_MAIL VARCHAR (50) NOT NULL,
TELEFONO INT NOT NULL,
ID_PROVINCIA INT NOT NULL,
CONSTRAINT PK_ID_SUCURSAL PRIMARY KEY (ID_SUCURSAL),
CONSTRAINT FK_ID_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIAS (ID_PROVINCIA)
)

-- TABLA COMPROBANTES
CREATE TABLE COMPROBANTES(
ID_COMPROBANTE INT IDENTITY (1,1),
FECHA_COMPROBANTE DATE NOT NULL,
IDTIPO_VENTA INT NOT NULL,
IDFORMA_PAGO INT NOT NULL,
ID_SUCURSAL INT NOT NULL,
CONSTRAINT PK_ID_COMPROBANTE PRIMARY KEY (ID_COMPROBANTE),
CONSTRAINT FK_IDTIPO_VENTA FOREIGN KEY (IDTIPO_VENTA) REFERENCES TIPOS_VENTAS (IDTIPO_VENTA),
CONSTRAINT FK_IDFORMA_PAGO FOREIGN KEY (IDFORMA_PAGO) REFERENCES FORMAS_PAGO (IDFORMA_PAGO),
CONSTRAINT FK_ID_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES (ID_SUCURSAL)
)

-- TABLA SALAS
CREATE TABLE SALAS(
ID_SALA INT IDENTITY (1,1)  ,
DESCRIPCION VARCHAR (100) NOT NULL,
IDTIPO_SALA INT NOT NULL,
CONSTRAINT PK_ID_SALA PRIMARY KEY (ID_SALA),
CONSTRAINT FK_IDTIPO_SALA FOREIGN KEY (IDTIPO_SALA) REFERENCES TIPOS_SALAS (IDTIPO_SALA)
)

-- TABLA BUTACAS
CREATE TABLE BUTACAS(
ID_BUTACA INT IDENTITY (1,1)  ,
DESCRIPCION VARCHAR (20) NOT NULL,
ID_SALA INT NOT NULL,
CONSTRAINT PK_ID_BUTACA PRIMARY KEY (ID_BUTACA),
CONSTRAINT FK_ID_SALA FOREIGN KEY (ID_SALA) REFERENCES SALAS (ID_SALA)
)

-- TABLA PELICULAS
CREATE TABLE PELICULAS(
ID_PELICULA INT IDENTITY (1,1)  ,
NOMBRE VARCHAR (100) NOT NULL,
DURACION INT NOT NULL,
AÑO_ESTRENO DATE NOT NULL,
ID_CLASIFICACION INT NOT NULL,
ID_VERSION INT NOT NULL,
IDGENERO_PELICULA INT NOT NULL,
CONSTRAINT PK_ID_PELICULA PRIMARY KEY (ID_PELICULA),
CONSTRAINT FK_ID_CLASIFICACION FOREIGN KEY (ID_CLASIFICACION) REFERENCES CLASIFICACIONES (ID_CLASIFICACION),
CONSTRAINT FK_ID_VERSION FOREIGN KEY (ID_VERSION) REFERENCES VERSIONES (ID_VERSION),
CONSTRAINT FK_IDGENERO_PELICULA FOREIGN KEY (IDGENERO_PELICULA) REFERENCES GENEROS_PELICULAS (IDGENERO_PELICULA)
)

-- TABLA FUNCIONES
CREATE TABLE FUNCIONES(
ID_FUNCION INT IDENTITY (1,1)  ,
HORA TIME NOT NULL,
FECHA DATE NOT NULL,
CONSTRAINT PK_ID_FUNCION PRIMARY KEY (ID_FUNCION),
)

--TABLA FUNCIONESXPELICULAS
CREATE TABLE FUNCIONESXPELICULAS(
ID_FUNCIONXPELICULA INT IDENTITY (1,1),
ID_FUNCION INT NOT NULL,
ID_PELICULA INT NOT NULL,
CONSTRAINT PK_FUNCIONESXPELICULAS PRIMARY KEY(ID_FUNCIONXPELICULA),
CONSTRAINT FK_FUNCIONESXPELICULAS_FUNCIONES FOREIGN KEY (ID_FUNCION) REFERENCES FUNCIONES (ID_FUNCION),
CONSTRAINT FK_FUNCIONESXPELICULAS_PELICULAS FOREIGN KEY (ID_PELICULA) REFERENCES PELICULAS (ID_PELICULA)
)

-- TABLA TICKETS
CREATE TABLE TICKETS(
ID_TICKET INT IDENTITY (1,1)  ,
ID_COMPROBANTE INT NOT NULL,
ID_FUNCIONXPELICULA INT NOT NULL,
IDTIPO_ENTRADA INT NOT NULL,
ID_BUTACA INT NOT NULL,
CONSTRAINT PK_ID_TICKET PRIMARY KEY (ID_TICKET),
CONSTRAINT FK_ID_COMPROBANTE FOREIGN KEY (ID_COMPROBANTE) REFERENCES COMPROBANTES (ID_COMPROBANTE),
CONSTRAINT FK_ID_FUNCIONXPELICULA FOREIGN KEY (ID_FUNCIONXPELICULA) REFERENCES FUNCIONESXPELICULAS (ID_FUNCIONXPELICULA),
CONSTRAINT FK_IDTIPO_ENTRADA FOREIGN KEY (IDTIPO_ENTRADA) REFERENCES TIPOS_ENTRADAS (IDTIPO_ENTRADA),
CONSTRAINT FK_ID_BUTACA FOREIGN KEY (ID_BUTACA) REFERENCES BUTACAS (ID_BUTACA)
)


--TABLA RESERVAS
CREATE TABLE RESERVAS(
ID_RESERVA INT IDENTITY (1,1)  ,
ID_TICKET INT NOT NULL,
ID_CLIENTE INT NOT NULL,
CONSTRAINT PK_ID_RESERVA PRIMARY KEY (ID_RESERVA),
CONSTRAINT FK_ID_TICKET FOREIGN KEY (ID_TICKET) REFERENCES TICKETS (ID_TICKET),
CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
)

--TABLA DETALLES COMPROBANTES
CREATE TABLE DETALLES_COMPROBANTES(
IDDETALLE_COMPROBANTE INT IDENTITY (1,1)  ,
MONTO DECIMAL (4,2) NOT NULL,
CANTIDAD INT NOT NULL,
ID_PROMOCION INT,
ID_COMPROBANTE INT NOT NULL,
CONSTRAINT PK_IDDETALLE_COMPROBANTE PRIMARY KEY (IDDETALLE_COMPROBANTE),
CONSTRAINT FK_ID_DETALLE_PROMOCION FOREIGN KEY (ID_PROMOCION) REFERENCES PROMOCIONES (ID_PROMOCION),
CONSTRAINT FK_ID_DETALLE_COMPROBANTE FOREIGN KEY (ID_COMPROBANTE) REFERENCES COMPROBANTES (ID_COMPROBANTE)
)               

-- TIPOS DNI
INSERT INTO TIPOS_DOCUMENTOS VALUES ('DOCUMENTO NACIONAL DE IDENTIDAD')
INSERT INTO TIPOS_DOCUMENTOS VALUES ('LIBRETA CIVICA')
INSERT INTO TIPOS_DOCUMENTOS VALUES ('LIBRETA DE ENROLAMIENTO')
INSERT INTO TIPOS_DOCUMENTOS VALUES ('CEDULA DE IDENTIDAD')
INSERT INTO TIPOS_DOCUMENTOS VALUES ('PASAPORTE')

--GENEROS
insert into GENEROS (DESCRIPCION) values ('Feminino')
insert into GENEROS (DESCRIPCION) values ('Masculino')
insert into GENEROS (DESCRIPCION) values ('Transexual')
insert into GENEROS (DESCRIPCION) values ('Otro')

--TIPOS PROVINCIAS 
insert into PROVINCIAS values ('Cordoba')
insert into PROVINCIAS values ('Santa Fe')
insert into PROVINCIAS values ('Buenos Aires')
insert into PROVINCIAS values ('Misiones')
insert into PROVINCIAS values ('Chaco')--5
insert into PROVINCIAS values ('Rio Negro')
insert into PROVINCIAS values ('Formosa')
insert into PROVINCIAS values ('Tucuman')
insert into PROVINCIAS values ('Rosario')
insert into PROVINCIAS values ('Parana')--10


--FORMAS_PAGO
insert into FORMAS_PAGO values('TARJETAS DE CREIDO')
insert into FORMAS_PAGO values('TARJETA DE DEBITO')
insert into FORMAS_PAGO values('PAYPAL')
insert into FORMAS_PAGO values('EFECTIVO')


--TIPO_VENTA
INSERT INTO TIPOS_VENTAS (DESCRIPCION) VALUES ('INTERNET')
INSERT INTO TIPOS_VENTAS (DESCRIPCION) VALUES ('VENTANILLA')

--PROMOCIONES
insert into PROMOCIONES values ('15%')
insert into PROMOCIONES values ('20%')
insert into PROMOCIONES values ('50%')
insert into PROMOCIONES values ('2x1')
insert into PROMOCIONES values ('Palomitas Gratis')--5
insert into PROMOCIONES values ('Bebida Gratis')

--CLASIFICACIONES
insert into CLASIFICACIONES values ('AA','Películas para todo público con atractivo infantil y sean comprensibles para menores de siete años.')
insert into CLASIFICACIONES values ('A','Películas para todo público.')
insert into CLASIFICACIONES values ('B','Películas para adolescentes de 13 años en adelante.')
insert into CLASIFICACIONES values ('B15','Película no recomendable para menores de 16 años de edad.')
insert into CLASIFICACIONES values ('C','Películas para adultos de 18 años en adelante.')--5
insert into CLASIFICACIONES values ('D','Películas para adultos, con sexo explícito, lenguaje procaz o alto grado de violencia.')

--GENEROS_PELICULAS
INSERT INTO GENEROS_PELICULAS VALUES('ANIMACION')
INSERT INTO GENEROS_PELICULAS VALUES('ACCION')
INSERT INTO GENEROS_PELICULAS VALUES('CIENCIA FICCION')
INSERT INTO GENEROS_PELICULAS VALUES('CRIMEN')
INSERT INTO GENEROS_PELICULAS VALUES('COMEDIA')--5
INSERT INTO GENEROS_PELICULAS VALUES('DOCUMENTAL')
INSERT INTO GENEROS_PELICULAS VALUES('DRAMA')
INSERT INTO GENEROS_PELICULAS VALUES('FANTASIA')
INSERT INTO GENEROS_PELICULAS VALUES('HISTORICO')
INSERT INTO GENEROS_PELICULAS VALUES('MELODRAMA')--10
INSERT INTO GENEROS_PELICULAS VALUES('MUSICAL')
INSERT INTO GENEROS_PELICULAS VALUES('ROMANCE')
INSERT INTO GENEROS_PELICULAS VALUES('SUSPENSO')
INSERT INTO GENEROS_PELICULAS VALUES('TERROR')
INSERT INTO GENEROS_PELICULAS VALUES('TRAGICOMEDIA')--15
INSERT INTO GENEROS_PELICULAS VALUES('WESTERN')

--VERSIONES
INSERT INTO VERSIONES (DESCRIPCION) VALUES ('VERSION ORIGINAL')
INSERT INTO VERSIONES (DESCRIPCION) VALUES ('VERSION ORIGINAL SUBTITULADA')
INSERT INTO VERSIONES (DESCRIPCION) VALUES ('VERSION ORIGINAL SUBTITULADA ESPAÑOL')
INSERT INTO VERSIONES (DESCRIPCION) VALUES ('VERSION DOBLADA ESPALÑOL')
INSERT INTO VERSIONES (DESCRIPCION) VALUES ('VERSION DOBLADA LATINO')--5
INSERT INTO VERSIONES (DESCRIPCION) VALUES ('VERSION DOBLADA ALEMAN')
INSERT INTO VERSIONES (DESCRIPCION) VALUES ('VERSION SORDOMUDO')

--TIPOS ENTRADAS
insert into TIPOS_ENTRADAS values ('Adulto')
insert into TIPOS_ENTRADAS values ('Niño')
insert into TIPOS_ENTRADAS values ('Adulto Mayor')

--TIPOS_SALAS
insert into TIPOS_SALAS(NOMBRE, DESCRIPCION, PRECIO) values ('2D','Visión en dos dimensiones',150)
insert into TIPOS_SALAS(NOMBRE, DESCRIPCION, PRECIO) values ('3D','Simula la visión tridimensional',250)
insert into TIPOS_SALAS(NOMBRE, DESCRIPCION, PRECIO) values ('4D','Butacas móviles con efectos especiales: Viento, agua, vibración, impacto y aromas',500)
insert into TIPOS_SALAS(NOMBRE, DESCRIPCION, PRECIO) values ('XD','Una pantalla gigante de piso a techo y de pared a pared, en formato 2D y 3D', 350)
insert into TIPOS_SALAS(NOMBRE, DESCRIPCION, PRECIO) values ('DBOX','Butacas programadas para moverse según los efectos especiales de la película en los formatos 2D y 3D',350)--5
insert into TIPOS_SALAS(NOMBRE, DESCRIPCION, PRECIO) values ('HDR',' Imágenes mucho más luminosas en cuanto a brillos, negros, reflejos y fundamentalmente la sensación de realidad que ofrecen. ',400)

--CLIENTES
INSERT INTO CLIENTES VALUES ('Alejandra', 'Garcia',1, 33523698, 'Pedro Zanni 1234, Alberdi','1988-09-09', 'alejandragarcia@gmail.com', 351749988, 1)
INSERT INTO CLIENTES VALUES ('Carlos', 'Pacheco',1,42256894,'Jerónimo Luis de Cabrera 154, Crisol','1999-10-10','carlospachechoa@gmail.com', 3516691632,2)
INSERT INTO CLIENTES VALUES ('Cristian', 'Sanchez',4,39974456,'Bv. San Juan 1250, Observatorio','1993-05-05','sanchezcristi@gmail.com', NULL,2)
INSERT INTO CLIENTES VALUES ('Javier', 'Moreno',1,36256895,'Ituzaingó 617, Centro','1996-01-28','morenojaviera@gmail.com', 3515362000,2)
INSERT INTO CLIENTES VALUES ('Emanuel', 'Montoya',1,28789654,'Hector Paniza 1230, Los Naranjos','1980-02-26','emanuelmontoya@gmail.com', 3518031402,3)
INSERT INTO CLIENTES VALUES ('Ariel', 'Mollo',1,40562874,'Gral. Paz 1456, Independencia','1997-03-10','arielmollo@gmail.com', 3516223366,2)
INSERT INTO CLIENTES VALUES ('Milagros', 'Navarro',1,23561278,'Cochabamba 1765, Pueyrredon','1973-04-02','navarromilagros@gmail.com', NULL,2)
INSERT INTO CLIENTES VALUES ('Patrica', 'Nieto',1,41379152,'Rondeau 210, Nueva Cordoba','1998-05-04','patricianieto@gmail.com', 3517033695,1)
INSERT INTO CLIENTES VALUES ('Gabriela', 'Ocampo',1,20897856,'24 de Septiembre 980, General Paz','1997-06-13','ocampogabriela@gmail.com', 3515332244,1)
INSERT INTO CLIENTES VALUES ('Victor', 'Oliva',5,29561273,'Av. Fuerza Aerea 2656, Los Naranjos','1982-07-07','victoroliva@gmail.com', 3517003020,2)
INSERT INTO CLIENTES VALUES ('Daniela', 'Paez',1,18236589,'Av. Rafael Nuñez 3569, Cerro de las Rosas','1967-08-10','danielapaez@gmail.com', 3515336697,1)
INSERT INTO CLIENTES VALUES ('Aldana', 'Cornejo',1,40123456,'Bv. Los Alemanes 5870, Jardines del Claret','1999-09-30','aldanacornejo@gmail.com', 3513569840,3)
INSERT INTO CLIENTES VALUES ('Valeria', 'Diaz',1,36589632,'Uritorco 3630, Rosedal','1986-11-26','valeriadiaz@gmail.com', NULL,1)
INSERT INTO CLIENTES VALUES ('Facundo', 'Diaz',1,38564123,'Duarte Quiros 2657, Alto Alberdi','1995-12-24','facundodiaz@gmail.com', 3518962364,2)
INSERT INTO CLIENTES VALUES ('Estefania', 'Garcia',1,34569824,'Balcarce 650, Nueva Cordoba','1989-01-22','estefaniagarcia@gmail.com', 3517530246,1)
INSERT INTO CLIENTES VALUES ('Lorenzo', 'Sanchez',1,39631489,'Agustin Garzon 3450, San Vicente','1996-02-15','lorenzogarcia@gmail.com', 3516980023,2)
INSERT INTO CLIENTES VALUES ('Nicolas', 'Gonzalez',1,42036970,'Garazza 1701, Yofre Norte','2000-03-29','nicolegonzalez@gmail.com', 3512003266,2)
INSERT INTO CLIENTES VALUES ('Tomas', 'Gonzalez',1,47563001,'Nuevo Mundo 923, Residencial America','2005-04-22','tomasgonzalez@gmail.com', 3512365990,3)
INSERT INTO CLIENTES VALUES ('Agustina', 'Montoya',1,50002360,'Blas Pascal 5498, Villa Belgrano','2008-05-08','agustinmontoya@gmail.com', NULL,1)
INSERT INTO CLIENTES VALUES ('Sabrina', 'Ferreyra',1,48560023,'Av. Don Bosco 450, Las Palmas','2001-06-01','ferreyrasabrina@gmail.com', 3516320169,3)
INSERT INTO CLIENTES VALUES ('Denise', 'Frias',2,14259325,'Esperanza 3126, Jardin','1961-07-06','denisefrias@gmail.com', 3515663320,3)
INSERT INTO CLIENTES VALUES ('Angel', 'Cabrera',2,23002360,'Diego Diaz 452, Marques de Sobremonte','1970-08-08','angelcabrera@gmail.com', 3516332145,2)
INSERT INTO CLIENTES VALUES ('Bautista', 'Calderon',2,28563256,'Cabo Oviedo 710, Jorge Newbery','1975-09-06','calderonbautista@gmail.com', NULL,2)
INSERT INTO CLIENTES VALUES ('Oscar', 'Ceballos',1,42555693,'Champaqui 3170, ATE','2000-11-11','oscarceballos@gmail.com', 3517896320,2)
INSERT INTO CLIENTES VALUES ('Leonel', 'Zeballos',1,47003625,'Bogota 1250, Villa el Libertador','2005-12-10','leonelazeballos@gmail.com', 3516982536,2)


--SUCURSALES
insert into SUCURSALES(NOMBRE_FANTASIA, RAZON_SOCIAL, CUIT, ING_BRUTO, DIRECCION, E_MAIL, TELEFONO, ID_PROVINCIA) 
values ('Estrellas Ruta 20', 'Estrellas SRL', 234035981, 300000,'Elpidio Gonzalez 1234','ruta20@estrellas.com', 35126598, 1)

insert into SUCURSALES(NOMBRE_FANTASIA, RAZON_SOCIAL, CUIT, ING_BRUTO, DIRECCION, E_MAIL, TELEFONO, ID_PROVINCIA) 
values ('Estrellas Calamuchita', 'Estrellas SRL',236985981, 500000,'San Martin 4564','calamuchita@estrellas.com', 35126598, 1)

insert into SUCURSALES(NOMBRE_FANTASIA, RAZON_SOCIAL, CUIT, ING_BRUTO, DIRECCION, E_MAIL, TELEFONO, ID_PROVINCIA) 
values ('Estrellas Moron', 'Estrellas SRL',234698981, 450000,'Trejo 326','moron@estrellas.com', 11648268, 3)

insert into SUCURSALES(NOMBRE_FANTASIA, RAZON_SOCIAL, CUIT, ING_BRUTO, DIRECCION, E_MAIL, TELEFONO, ID_PROVINCIA) 
values ('Estrellas Trejo', 'Estrellas SRL',234015891, 200000,'Uriarte 1869','trejo@estrellas.com', 354823268, 7)

insert into SUCURSALES(NOMBRE_FANTASIA, RAZON_SOCIAL, CUIT, ING_BRUTO, DIRECCION, E_MAIL, TELEFONO, ID_PROVINCIA) 
values ('Estrellas Sarmiento', 'Estrellas SRL',225832369, 350000,'Azquenaga 162','sarmiento@estrellas.com', 358245598, 1)

insert into SUCURSALES(NOMBRE_FANTASIA, RAZON_SOCIAL, CUIT, ING_BRUTO, DIRECCION, E_MAIL, TELEFONO, ID_PROVINCIA) 
values ('Estrellas Rosario', 'Estrellas SRL',257232981, 520000,'Julio Roca 6248','rosario@estrellas.com', 11648298, 9)

insert into SUCURSALES(NOMBRE_FANTASIA, RAZON_SOCIAL, CUIT, ING_BRUTO, DIRECCION, E_MAIL, TELEFONO, ID_PROVINCIA) 
values ('Estrellas Paraná', 'Estrellas SRL',269832661, 270000,'San Diego 3691','parana@estrellas.com', 362983568, 10)

--COMPROBANTES
INSERT INTO COMPROBANTES VALUES('29-09-2019',1, 4,1)
INSERT INTO COMPROBANTES VALUES('29-09-2019',1, 2,1)
INSERT INTO COMPROBANTES VALUES('30-09-2019',1, 2,1)
INSERT INTO COMPROBANTES VALUES('2-10-2019',2, 1,1)
INSERT INTO COMPROBANTES VALUES('2-10-2019',2, 3,1)--5
INSERT INTO COMPROBANTES VALUES('2-10-2019',2, 4,1)
INSERT INTO COMPROBANTES VALUES('3-10-2019',1, 1,1)
INSERT INTO COMPROBANTES VALUES('4-10-2019',2, 4,1)
INSERT INTO COMPROBANTES VALUES('4-10-2019',2, 1,1)
INSERT INTO COMPROBANTES VALUES('4-10-2019',1, 2,1)--10
INSERT INTO COMPROBANTES VALUES('5-10-2019',2, 4,1)
INSERT INTO COMPROBANTES VALUES('7-10-2019',2, 3,1)
INSERT INTO COMPROBANTES VALUES('7-10-2019',1, 4,1)
INSERT INTO COMPROBANTES VALUES('8-10-2019',2, 2,1)
INSERT INTO COMPROBANTES VALUES('9-10-2019',1, 4,1)--15
INSERT INTO COMPROBANTES VALUES('9-10-2019',2, 4,1)
INSERT INTO COMPROBANTES VALUES('10-10-2019',2, 2,1)
INSERT INTO COMPROBANTES VALUES('10-10-2019',1, 4,1)
INSERT INTO COMPROBANTES VALUES('11-10-2019',2, 1,1)

--SALAS 
INSERT INTO SALAS VALUES('PRIMERA SALA A LA DERECHA',1)
INSERT INTO SALAS VALUES('PRIMERA SALA A LA IZQUIERDA',2)
INSERT INTO SALAS VALUES('SEGUNDA SALA A LA DERECHA',1)
INSERT INTO SALAS VALUES('SEGUNDA SALA A LA IZQUIERA',3)
INSERT INTO SALAS VALUES('TERCERA SALA A LA DERECHA',1)--5
INSERT INTO SALAS VALUES('TERCERA SALA A LA IZQUIERDA',2)
INSERT INTO SALAS VALUES('CUARTA SALA A LA DERECHA',4)
INSERT INTO SALAS VALUES('QUINTA SALA A LA DERECHA',3)
INSERT INTO SALAS VALUES('QUINTA SALA A LA IZQUIERDA',1)
INSERT INTO SALAS VALUES('SEXTA SALA A LA IZQUIERDA',5)--10


--BUTACAS
insert into BUTACAS values ('H1',1)
insert into BUTACAS values ('H2',1)
insert into BUTACAS values ('H3',1)
insert into BUTACAS values ('H4',1)
insert into BUTACAS values ('H5',1)
insert into BUTACAS values ('G1',1)
insert into BUTACAS values ('G2',1)
insert into BUTACAS values ('G3',1)
insert into BUTACAS values ('G4',1)
insert into BUTACAS values ('G5',1)
insert into BUTACAS values ('F1',1)
insert into BUTACAS values ('F2',1)
insert into BUTACAS values ('F3',1)
insert into BUTACAS values ('F4',1)
insert into BUTACAS values ('F5',1)--15
insert into BUTACAS values ('H1',2)
insert into BUTACAS values ('H2',2)
insert into BUTACAS values ('H3',2)
insert into BUTACAS values ('H4',2)
insert into BUTACAS values ('H5',2)
insert into BUTACAS values ('G1',2)
insert into BUTACAS values ('G2',2)
insert into BUTACAS values ('G3',2)
insert into BUTACAS values ('G4',2)
insert into BUTACAS values ('G5',2)
insert into BUTACAS values ('F1',2)
insert into BUTACAS values ('F2',2)
insert into BUTACAS values ('F3',2)
insert into BUTACAS values ('F4',2)
insert into BUTACAS values ('F5',2)--30
insert into BUTACAS values ('H1',3)
insert into BUTACAS values ('H2',3)
insert into BUTACAS values ('H3',3)
insert into BUTACAS values ('H4',3)
insert into BUTACAS values ('H5',3)
insert into BUTACAS values ('G1',3)
insert into BUTACAS values ('G2',3)
insert into BUTACAS values ('G3',3)
insert into BUTACAS values ('G4',3)
insert into BUTACAS values ('G5',3)
insert into BUTACAS values ('F1',3)
insert into BUTACAS values ('F2',3)
insert into BUTACAS values ('F3',3)
insert into BUTACAS values ('F4',3)
insert into BUTACAS values ('F5',3)--45
insert into BUTACAS values ('H1',4)
insert into BUTACAS values ('H2',4)
insert into BUTACAS values ('H3',4)
insert into BUTACAS values ('H4',4)
insert into BUTACAS values ('H5',4)
insert into BUTACAS values ('G1',4)
insert into BUTACAS values ('G2',4)
insert into BUTACAS values ('G3',4)
insert into BUTACAS values ('G4',4)
insert into BUTACAS values ('G5',4)
insert into BUTACAS values ('F1',4)
insert into BUTACAS values ('F2',4)
insert into BUTACAS values ('F3',4)
insert into BUTACAS values ('F4',4)
insert into BUTACAS values ('F5',4)--60
insert into BUTACAS values ('H1',5)
insert into BUTACAS values ('H2',5)
insert into BUTACAS values ('H3',5)
insert into BUTACAS values ('H4',5)
insert into BUTACAS values ('H5',5)
insert into BUTACAS values ('G1',5)
insert into BUTACAS values ('G2',5)
insert into BUTACAS values ('G3',5)
insert into BUTACAS values ('G4',5)
insert into BUTACAS values ('G5',5)
insert into BUTACAS values ('F1',5)
insert into BUTACAS values ('F2',5)
insert into BUTACAS values ('F3',5)
insert into BUTACAS values ('F4',5)
insert into BUTACAS values ('F5',5)--75
insert into BUTACAS values ('H1',6)
insert into BUTACAS values ('H2',6)
insert into BUTACAS values ('H3',6)
insert into BUTACAS values ('H4',6)
insert into BUTACAS values ('H5',6)
insert into BUTACAS values ('G1',6)
insert into BUTACAS values ('G2',6)
insert into BUTACAS values ('G3',6)
insert into BUTACAS values ('G4',6)
insert into BUTACAS values ('G5',6)
insert into BUTACAS values ('F1',6)
insert into BUTACAS values ('F2',6)
insert into BUTACAS values ('F3',6)
insert into BUTACAS values ('F4',6)
insert into BUTACAS values ('F5',6)--90
insert into BUTACAS values ('H1',7)
insert into BUTACAS values ('H2',7)
insert into BUTACAS values ('H3',7)
insert into BUTACAS values ('H4',7)
insert into BUTACAS values ('H5',7)
insert into BUTACAS values ('G1',7)
insert into BUTACAS values ('G2',7)
insert into BUTACAS values ('G3',7)
insert into BUTACAS values ('G4',7)
insert into BUTACAS values ('G5',7)
insert into BUTACAS values ('F1',7)
insert into BUTACAS values ('F2',7)
insert into BUTACAS values ('F3',7)
insert into BUTACAS values ('F4',7)
insert into BUTACAS values ('F5',7)--105
insert into BUTACAS values ('H1',8)
insert into BUTACAS values ('H2',8)
insert into BUTACAS values ('H3',8)
insert into BUTACAS values ('H4',8)
insert into BUTACAS values ('H5',8)
insert into BUTACAS values ('G1',8)
insert into BUTACAS values ('G2',8)
insert into BUTACAS values ('G3',8)
insert into BUTACAS values ('G4',8)
insert into BUTACAS values ('G5',8)
insert into BUTACAS values ('F1',8)
insert into BUTACAS values ('F2',8)
insert into BUTACAS values ('F3',8)
insert into BUTACAS values ('F4',8)
insert into BUTACAS values ('F5',8)--120
insert into BUTACAS values ('H1',9)
insert into BUTACAS values ('H2',9)
insert into BUTACAS values ('H3',9)
insert into BUTACAS values ('H4',9)
insert into BUTACAS values ('H5',9)
insert into BUTACAS values ('G1',9)
insert into BUTACAS values ('G2',9)
insert into BUTACAS values ('G3',9)
insert into BUTACAS values ('G4',9)
insert into BUTACAS values ('G5',9)
insert into BUTACAS values ('F1',9)
insert into BUTACAS values ('F2',9)
insert into BUTACAS values ('F3',9)
insert into BUTACAS values ('F4',9)
insert into BUTACAS values ('F5',9)--135
insert into BUTACAS values ('H1',10)
insert into BUTACAS values ('H2',10)
insert into BUTACAS values ('H3',10)
insert into BUTACAS values ('H4',10)
insert into BUTACAS values ('H5',10)
insert into BUTACAS values ('G1',10)
insert into BUTACAS values ('G2',10)
insert into BUTACAS values ('G3',10)
insert into BUTACAS values ('G4',10)
insert into BUTACAS values ('G5',10)
insert into BUTACAS values ('F1',10)
insert into BUTACAS values ('F2',10)
insert into BUTACAS values ('F3',10)
insert into BUTACAS values ('F4',10)
insert into BUTACAS values ('F5',10)--150

--PELICULAS
INSERT INTO PELICULAS VALUES ('¿QUIEN MATO A MI HERMANO?',76,'15/09/2019',4,5,6)--1
INSERT INTO PELICULAS VALUES ('ASÍ HABLÓ EL CAMBISTA',82,'18/09/2019',4,5,15)--2
INSERT INTO PELICULAS VALUES ('HISTORIAS DE MIEDO PARA CONTAR EN LA OSCURIDAD',120,'21/09/2019',5,5,14)--3
INSERT INTO PELICULAS VALUES ('HISTORIAS DE MIEDO PARA CONTAR EN LA OSCURIDAD',120,'21/09/2019',5,3,14)
INSERT INTO PELICULAS VALUES ('MUJER EN GUERRA',88,'23/09/2019',4,5,2)--5
INSERT INTO PELICULAS VALUES ('NUESTROS VERANOS',120,'23/09/2019',2,5,15)
INSERT INTO PELICULAS VALUES ('PÁJAROS EN VERANO',125,'26/09/2019',4,2,4)
INSERT INTO PELICULAS VALUES ('UN AMIGO ABOMINABLE',82,'26/09/2019',1,5,5)
INSERT INTO PELICULAS VALUES ('AD ASTRA:HACIA LAS ESTRELLAS',123,'29/09/2019',3,3,3)
INSERT INTO PELICULAS VALUES ('INICIALES S.G.',83,'29/09/2019',3,1,5)--10
INSERT INTO PELICULAS VALUES ('NADA QUE PERDER 2',120,'30/09/2019',5,5,6)
INSERT INTO PELICULAS VALUES ('PRESIDENTE BAJO FUEGO',91,'26/09/2019',3,5,2)
INSERT INTO PELICULAS VALUES ('SR. LINK',80,'20/09/2019',1,5,1)
INSERT INTO PELICULAS VALUES ('YESTERDAY',97,'23/09/2019',3,5,15)
INSERT INTO PELICULAS VALUES ('IT: CAPITULO 2',150,'18/09/2019',4,5,14)--15
INSERT INTO PELICULAS VALUES ('IT: CAPITULO 2',150,'18/09/2019',4,3,14)
INSERT INTO PELICULAS VALUES ('DORA Y LA CIUDAD PERDIDA',85,'29/09/2019',1,5,8)
INSERT INTO PELICULAS VALUES ('HABIA UNA VEZ EN HOLLYWOOD',145,'26/09/2019',4,3,15)
INSERT INTO PELICULAS VALUES ('PAW PATROL: MIGHTY PUPS',73,'29/09/2019',1,5,1)
INSERT INTO PELICULAS VALUES ('ANDRY BIRDS 2: LA PELÍCULA',82,'26/09/2019',1,5,1)
INSERT INTO PELICULAS VALUES ('LA ODISEA DE LO GILES',93,'29/09/2019',3,1,15)--20
INSERT INTO PELICULAS VALUES ('EL REY LEÓN',94,'30/09/2019',2,5,1)

--FUNCIONES
insert into FUNCIONES values ('9:00:00 AM','29-09-2019')
insert into FUNCIONES values ('3:20:00 PM','30-09-2019')
insert into FUNCIONES values ('8:00:00 AM','2-10-2019')
insert into FUNCIONES values ('4:30:00 PM','3-10-2019')
insert into FUNCIONES values ('9:00:00 AM','4-10-2019')--5
insert into FUNCIONES values ('12:00:00 AM','5-10-2019')
insert into FUNCIONES values ('7:15:00 PM','5-10-2019')
insert into FUNCIONES values ('2:00:00 PM','6-10-2019')
insert into FUNCIONES values ('7:00:00 PM','7-10-2019')
insert into FUNCIONES values ('9:30:00 AM','7-10-2019')--10
insert into FUNCIONES values ('1:00:00 PM','8-10-2019')
insert into FUNCIONES values ('5:30:00 PM','9-10-2019')
insert into FUNCIONES values ('6:00:00 PM','10-10-2019')
insert into FUNCIONES values ('6:40:00 PM','10-10-2019')
insert into FUNCIONES values ('11:00:00 AM','11-10-2019')--15


--FUNCIONESXPELICULAS
INSERT INTO FUNCIONESXPELICULAS VALUES (1,3)
INSERT INTO FUNCIONESXPELICULAS VALUES (1,5)
INSERT INTO FUNCIONESXPELICULAS VALUES (5,6)
INSERT INTO FUNCIONESXPELICULAS VALUES (15,4)
INSERT INTO FUNCIONESXPELICULAS VALUES (9,18)--5
INSERT INTO FUNCIONESXPELICULAS VALUES (6,9)
INSERT INTO FUNCIONESXPELICULAS VALUES (5,1)
INSERT INTO FUNCIONESXPELICULAS VALUES (9,6)
INSERT INTO FUNCIONESXPELICULAS VALUES (6,20)
INSERT INTO FUNCIONESXPELICULAS VALUES (11,15)--10
INSERT INTO FUNCIONESXPELICULAS VALUES (12,16)
INSERT INTO FUNCIONESXPELICULAS VALUES (10,17)
INSERT INTO FUNCIONESXPELICULAS VALUES (2,13)
INSERT INTO FUNCIONESXPELICULAS VALUES (3,20)
INSERT INTO FUNCIONESXPELICULAS VALUES (8,8)--15
INSERT INTO FUNCIONESXPELICULAS VALUES (13,1)
INSERT INTO FUNCIONESXPELICULAS VALUES (15,3)
INSERT INTO FUNCIONESXPELICULAS VALUES (9,9)
INSERT INTO FUNCIONESXPELICULAS VALUES (15,7)--19
INSERT INTO FUNCIONESXPELICULAS VALUES (9,19)
INSERT INTO FUNCIONESXPELICULAS VALUES (5,18)
INSERT INTO FUNCIONESXPELICULAS VALUES (5,13)
INSERT INTO FUNCIONESXPELICULAS VALUES (3,17)
INSERT INTO FUNCIONESXPELICULAS VALUES (7,11)
INSERT INTO FUNCIONESXPELICULAS VALUES (4,10)--25
INSERT INTO FUNCIONESXPELICULAS VALUES (1,5)
INSERT INTO FUNCIONESXPELICULAS VALUES (13,8)
INSERT INTO FUNCIONESXPELICULAS VALUES (14,6)
INSERT INTO FUNCIONESXPELICULAS VALUES (12,14)

--TICKETS
insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (1, 1, 1, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (2, 1, 1, 2)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (3, 2, 2, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (4, 3, 3, 3)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (5, 3, 3, 3)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (6, 3, 3, 2)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (7, 5, 4, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (8, 5, 4, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (9, 5, 4, 2)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (10, 5, 4, 2)--10

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (11, 5, 4, 2)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (16, 4, 5, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (17, 4, 5, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (14, 8, 6, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (15, 8, 6, 3)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (12, 8, 6, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (13, 8, 7, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (18, 8, 8, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (19, 9, 9, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (20, 9, 9, 2)--20

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (21, 9, 10, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA	, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (22, 9, 10, 2)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (23, 14, 11, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (24, 14, 11, 2)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (25, 14, 11, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (26, 14, 11, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (136, 10, 12, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (137, 10, 12, 3)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (138, 10, 12, 3)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (139, 10, 13, 3)--30

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (140, 10, 13, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (141, 10, 13, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (142, 10, 13, 2)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (143, 12, 14, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (144, 12, 14, 2)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (91, 6, 15, 2)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (92, 6, 15, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (93, 6, 15, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (94, 6, 16, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (95, 6, 16, 1)--40

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (96, 6, 16, 2)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (97, 6, 16, 3)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (98, 6, 16, 2)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (99, 6, 16, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (76, 1, 17, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (77, 1, 17, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (81, 2, 18, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (82, 2, 18, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (49, 4, 19, 1)

insert into TICKETS (ID_BUTACA, ID_FUNCIONXPELICULA, ID_COMPROBANTE, IDTIPO_ENTRADA) 
values (50, 4, 19, 2)--50




--RESERVAS
insert into RESERVAS values(1,1)
insert into RESERVAS values(2,2)
insert into RESERVAS values(3,3)
insert into RESERVAS values(4,4)
insert into RESERVAS values(5,5)
insert into RESERVAS values(6,6)
insert into RESERVAS values(7,7)
insert into RESERVAS values(8,8)
insert into RESERVAS values(9,9)
insert into RESERVAS values(10,10)

--DETALLES COMPROBANTE
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (60,2,6,5)
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (60,2,5,9)
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (60,6,4,16)
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (60,2,NULL,19)
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (80,1,1,7)--5
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (80,5,3,4)
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (80,3,2,6)
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (80,2,NULL,1)
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (90,2,NULL,18)--9
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (90,2,NULL,17)
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (90,1,6,2)
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (90,3,1,3)--12
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (90,1,NULL,8)
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (90,4,NULL,11)
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (90,2,6,10)--15
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (90,4,1,13)
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (90,3,NULL,15)
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (90,2,6,14)
INSERT INTO DETALLES_COMPROBANTES (MONTO, CANTIDAD, ID_PROMOCION, ID_COMPROBANTE) values (90,3,1,12)--19
----3) Se necesita conocer el promedio de facturación por comprobante -- OOOOKKKKK
select avg(MONTO*cantidad) 'prom x det fact',
	sum(MONTO*cantidad) / COUNT(distinct f.ID_COMPROBANTE) 'prom por factura'
	from DETALLES_COMPROBANTES d, COMPROBANTES f
	where d.ID_COMPROBANTE=f.ID_COMPROBANTE

----1) Se quiere saber si alguno de estos clientes: 1 a 6, si hicieron reservas. 
--Muestre solamente el nombre de la pelicula.
SELECT c.id_cliente 'Codigo Cliente', p.NOMBRE 'Pelicula'
FROM clientes c join reservas r on c.id_cliente=r.id_cliente
join tickets t on r.id_ticket=t.id_ticket
join funcionesxpeliculas fp on t.id_funcionxpelicula=fp.id_funcionxpelicula
join peliculas p on fp.id_pelicula=p.id_pelicula
where c.ID_CLIENTE between 1 and 6


--subconsula con having: Listar la cantidad total vendida, el importe y promedio vendido por fecha,
-- siempre que esa cantidad
----sea superior al promedio de la cantidad global. Rotule y ordene

--select c.fecha_comprobante, count(c.id_comprobante) as qtvendida,sum(dc.cantidad*dc.monto) importe,avg(dc.cantidad*dc.monto) promedio
--from comprobantes c, DETALLES_COMPROBANTES dc
--where c.ID_COMPROBANTE=dc.ID_COMPROBANTE
--group by c.FECHA_COMPROBANTE
--order by c.FECHA_COMPROBANTE

--subconsula con having: Listar la cantidad total vendida, el importe y promedio vendido por fecha,
-- siempre que esa cantidad
--sea superior al promedio de la cantidad global. Rotule y ordene -- si hay sumarias hay group by
select p.nombre, sum(dc.cantidad)
from DETALLES_COMPROBANTES dc, COMPROBANTES c, TICKETS t, FUNCIONESXPELICULAS fp, PELICULAS p
where dc.ID_COMPROBANTE=c.ID_COMPROBANTE
and c.ID_COMPROBANTE=t.ID_COMPROBANTE
and t.ID_FUNCIONXPELICULA=fp.ID_FUNCIONXPELICULA
and fp.ID_PELICULA=p.ID_PELICULA
group by p.NOMBRE 

--Subconsulta con Having: Listar la cantidad total vendida, el importe y promedio vendido por fecha,
--siempre que esa cantidad sea superior al promedio de la cantidad global. Rotular y ordenar
select p.nombre NombrePeli, avg(dc.cantidad) PromedioCant, sum(dc.cantidad) CantEntradas, sum(dc.MONTO) SumaMontos, sum(dc.cantidad*dc.monto) Importe, FECHA_COMPROBANTE Fecha
from detalles_comprobantes dc join comprobantes c on dc.id_comprobante=c.id_comprobante
join tickets t on c.id_comprobante=t.id_comprobante
join funcionesxpeliculas fp on t.id_funcionxpelicula=fp.id_funcionxpelicula
join peliculas p on fp.id_pelicula=p.id_pelicula
group by p.nombre, FECHA_COMPROBANTE
having avg(dc.cantidad) > (select avg(cantidad) from DETALLES_COMPROBANTES)--okkkkkkkkk


select*from DETALLES_COMPROBANTES where ID_COMPROBANTE = 14
select*from COMPROBANTES
select*from TICKETS where ID_FUNCIONXPELICULA =23
select*from FUNCIONESXPELICULAS where ID_PELICULA = 17
select*from PELICULAS

------2) el cliente que segun la forma de pago realizo sea uno
----select cl.APELLIDO +', '+ cl.NOMBRE as 'Nombre Completo', co.FECHA_COMPROBANTE as 'Fecha'
----from clientes cl, FORMAS_PAGO fp, RESERVAS r, TICKETS ti, COMPROBANTES co
----where cl.ID_CLIENTE=r.ID_CLIENTE
----and r.ID_TICKET=ti.ID_TICKET
----and ti.ID_COMPROBANTE= co.ID_COMPROBANTE
----and fp.IDFORMA_PAGO=co.IDFORMA_PAGO
----and fp.IDFORMA_PAGO=1
----order by 1

--select * from DETALLES_COMPROBANTES
